"""Builds directories.json and directories.csv from the rows below. MIT licensed."""
import csv, json

FIELDS = ["name", "url", "submit_url", "free_or_paid", "requires_account", "link_type", "review_time",
          "dr", "dr_source", "ai_agent_friendly", "submit_steps", "notes", "last_verified"]
ROWS = [{'name': 'Neeed Directory',
  'url': 'https://neeed.directory',
  'submit_url': 'https://neeed.directory/submit',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': 'yes',
  'link_type': 'dofollow',
  'review_time': 'Live right away after an automatic check',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'submit_steps': ['Pick a listing type',
                   'Sign in',
                   'Fill in the form',
                   'Automatic check runs',
                   'Listing goes live right away'],
  'notes': 'Software and digital products only. Free plan plus one-time paid options. Link type is '
           "the site's own statement.",
  'last_verified': '2026-10-05'},
 {'name': 'Startup Fame',
  'url': 'https://startupfa.me',
  'submit_url': '',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': 'yes',
  'link_type': 'dofollow_with_badge',
  'review_time': 'Several business days',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'submit_steps': [],
  'notes': "Submit URL not found (/submit returns 404). Free listing requires a badge on your site and a review; no-badge listing is paid (per the site's FAQ, checked 2026-10-08). Paid: Highlight $19/month, Spotlight $149/month. Link type is the site's own statement.",
  'last_verified': '2026-10-08'},
 {'name': 'TinyLaunch',
  'url': 'https://tinylaunch.com',
  'submit_url': 'https://tinylaunch.com/submit',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': 'yes',
  'link_type': 'dofollow_with_badge',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'submit_steps': ['Sign in with email, Google, GitHub or X',
                   'Submit the launch form',
                   'Embed the TinyLaunch badge on your site to get a dofollow link'],
  'notes': 'Free launch gets a dofollow link when the badge is embedded. Premium and done-for-you '
           'options are paid.',
  'last_verified': '2026-10-05'},
 {'name': 'Dev Hunt',
  'url': 'https://devhunt.org',
  'submit_url': '',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': '',
  'link_type': '',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'submit_steps': [],
  'notes': 'Submit URL not found. Launches are shown as Free. Ads cost $89/week.',
  'last_verified': '2026-10-05'},
 {'name': 'Findly',
  'url': 'https://findly.tools',
  'submit_url': 'https://findly.tools/submit',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': 'yes',
  'link_type': 'dofollow',
  'review_time': '',
  'dr': '81',
  'dr_source': 'Ahrefs, noted by Team Handyapps 2026-10-02',
  'ai_agent_friendly': '',
  'submit_steps': ['Sign in with email, GitHub or Google', 'Submit the product on /submit'],
  'notes': 'Free listing. Paid done-for-you option.',
  'last_verified': '2026-10-05'},
 {'name': 'ToolFame',
  'url': 'https://toolfame.com',
  'submit_url': 'https://toolfame.com/submit',
  'free_or_paid': '',
  'requires_account': 'yes',
  'link_type': '',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'submit_steps': ['Sign in with email, Google or GitHub', 'Submit the product on /submit'],
  'notes': 'Link type, pricing and review time not stated on the site.',
  'last_verified': '2026-10-05'},
 {'name': 'Nick Launches',
  'url': 'https://nicklaunches.com',
  'submit_url': 'https://nicklaunches.com/submit',
  'free_or_paid': '',
  'requires_account': '',
  'link_type': '',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': 'yes',
  'submit_steps': ['Open the submit form',
                   'Add a logo and screenshots',
                   'Pick a plan and a launch week',
                   'Save as a draft if needed'],
  'notes': 'Has an MCP server: claude mcp add --transport http nicklaunches '
           'https://nicklaunches.com/api/mcp/ (no key; approve in the browser; the agent drafts, a '
           'human finishes). Prices not read.',
  'last_verified': '2026-10-05'},
 {'name': 'Fazier',
  'url': 'https://fazier.com',
  'submit_url': 'https://fazier.com/submit',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': '',
  'link_type': '',
  'review_time': 'Within 30 days (Basic plan)',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'submit_steps': [],
  'notes': 'Basic plan is free. Paid tiers $29 and $49. A high-authority dofollow link is a paid '
           'perk.',
  'last_verified': '2026-10-05'},
 {'name': 'BetaList',
  'url': 'https://betalist.com',
  'submit_url': 'https://betalist.com/submit',
  'free_or_paid': '',
  'requires_account': 'yes',
  'link_type': '',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'submit_steps': ['Sign in with X or a magic link', 'Submit the startup on /submit'],
  'notes': 'Free or paid and link type not stated on the page read.',
  'last_verified': '2026-10-05'},
 {'name': 'LaunchFree',
  'url': 'https://launchfree.io/',
  'submit_url': 'https://launchfree.io/submit',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': '',
  'link_type': 'dofollow',
  'review_time': '24 hours (site-stated)',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Site-stated dofollow, not independently inspected on a published listing; no ranking '
           'gain established. Required builder name and bio: brand eligibility must be checked '
           'before submission. Optional sponsorship separate. Sources: https://launchfree.io/ ; '
           'https://launchfree.io/submit',
  'submit_steps': ['Enter launch name, URL and tagline (80 characters maximum)',
                   'Choose category, description (100-1200 characters), origin story, status and '
                   'pricing',
                   'Provide name, email and short bio; agree to terms',
                   'Submit for review'],
  'last_verified': '2026-10-07'},
 {'name': 'IndieLaunch',
  'url': 'https://indielaunch.dev/',
  'submit_url': 'https://indielaunch.dev/submit-your-startup',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': 'yes',
  'link_type': 'dofollow_with_badge',
  'review_time': 'Goes live the day approved; review duration not stated',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Without badge the free link is nofollow, according to FAQ. Premium offers dofollow '
           'without badge. Site states it exposes llms.txt and MCP; this is machine readability, '
           'not a verified submission API. Source: https://indielaunch.dev/submit-your-startup',
  'submit_steps': ['Sign in with an email code',
                   'Paste URL and review generated details',
                   'Optionally add and verify badge for dofollow',
                   'Submit for manual review'],
  'last_verified': '2026-10-07'},
 {'name': 'LetsLaunch',
  'url': 'https://letslaunch.today/',
  'submit_url': '',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': '',
  'link_type': 'dofollow_with_badge',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Free launches capped at 20/week; badge required by published FAQ. '
           'Five-upvotes-in-seven-days retention rule currently paused, subject to change. '
           'Markdown and llms-full.txt documented; no submission API verified. Submit URL and '
           'account requirement not verified. Do not treat site DR claim as checked DR. Sources: '
           'https://letslaunch.today/ ; https://letslaunch.today/developer-tools-directory',
  'submit_steps': ['Choose an available free launch week',
                   'Submit product',
                   'Place reciprocal badge and pass automatic badge check'],
  'last_verified': '2026-10-07'},
 {'name': '10015 Product Finder',
  'url': 'https://10015.io/',
  'submit_url': 'https://10015.io/product-finder/submit',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': '',
  'link_type': 'nofollow',
  'review_time': '3-4 months (free standard queue)',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Free listings nofollow per FAQ. Priority review and featured/dofollow options paid. '
           'Account requirement not verified. Source: https://10015.io/product-finder/submit',
  'submit_steps': ['Enter live product website URL',
                   'Review generated fields, categories and tags',
                   'Submit for manual review'],
  'last_verified': '2026-10-07'},
 {'name': 'mcp.tc',
  'url': 'https://mcp.tc/',
  'submit_url': 'https://mcp.tc/submit',
  'free_or_paid': 'free',
  'requires_account': 'no',
  'link_type': '',
  'review_time': 'Usually minutes for automated checks; unclear cases manual',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': 'yes',
  'notes': 'Documented JSON POST /submit accepts url and optional note; no key/account/charge. '
           'Leave personal data and secrets out. One listing per server; duplicate detection. '
           'Optional claiming later requires account/domain proof. Link type not verified. '
           'Sources: https://mcp.tc/submit ; https://mcp.tc/docs/server-owners ; '
           'https://mcp.tc/docs/api',
  'submit_steps': ['Submit public MCP endpoint, GitHub repository or npm/PyPI URL',
                   'Checker reads handshake and tools; ambiguous cases held for person',
                   'Follow returned status URL for listing or pending outcome'],
  'last_verified': '2026-10-07'},
 {'name': 'mcpi.app',
  'url': 'https://mcpi.app/',
  'submit_url': 'https://mcpi.app/',
  'free_or_paid': 'free',
  'requires_account': '',
  'link_type': '',
  'review_time': 'Immediately after domain-control verification',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Remote MCP endpoint directory; listing is free, no review queue according to own docs. '
           'Existing registry imports should be claimed, not duplicated. Domain proof required; '
           'account and outbound link type not verified. Source: '
           'https://mcpi.app/docs/directory/publish',
  'submit_steps': ['Search for existing listing before creating duplicate',
                   'Scan domain or fill publish card',
                   'Prove control using DNS TXT or well-known HTTP file',
                   'Verify and publish'],
  'last_verified': '2026-10-07'},
 {'name': 'mcpservers.org',
  'url': 'https://mcpservers.org/',
  'submit_url': 'https://mcpservers.org/submit',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': '',
  'link_type': '',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Free listings stated; review duration/account requirement not stated. $39 premium adds '
           'faster review, official badge and dofollow. Do not infer free link type from premium '
           'perk. Source: https://mcpservers.org/submit',
  'submit_steps': ['Enter server name, short description, GitHub/docs link, category and contact '
                   'email',
                   'Submit free listing'],
  'last_verified': '2026-10-07'},
 {'name': 'MCP Harbor Registry',
  'url': 'https://ai.mcpharbor.dev/',
  'submit_url': 'https://ai.mcpharbor.dev/submit',
  'free_or_paid': '',
  'requires_account': '',
  'link_type': '',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': 'yes',
  'notes': 'Documented JSON API POST /api/v0/servers and submit_server MCP tool. Manual review, '
           'not automatic publication. Pricing/account/link type not explicitly verified from '
           'submission page. Never include API secret values in environment variables. Source: '
           'https://ai.mcpharbor.dev/submit',
  'submit_steps': ['Provide reverse-DNS name, title, description, version and transport',
                   'Add remote URL for hosted transport or package identifier for stdio',
                   'Add tools, tags and optional repository/website/license',
                   'Submit into maintainer review queue'],
  'last_verified': '2026-10-07'},
 {'name': 'Tolodora',
  'url': 'https://tolodora.com/',
  'submit_url': 'https://tolodora.com/launch',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': '',
  'link_type': '',
  'review_time': 'Instant (site-stated)',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Site states no queue and free core listing; optional paid premium placement. Badge '
           'offered but no mandatory badge verified. Account requirement and followed-link status '
           'unknown. Software, SaaS, apps and services eligible per own page. Source: '
           'https://tolodora.com/launch',
  'submit_steps': ['Add name, logo, pitch, screenshots and website', 'Submit to publish'],
  'last_verified': '2026-10-07'},
 {'name': 'MCP Collection',
  'url': 'https://mcpcollection.com/',
  'submit_url': 'https://mcpcollection.com/submit',
  'free_or_paid': 'free',
  'requires_account': 'no',
  'link_type': '',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': 'yes',
  'notes': 'GET https://mcpcollection.com/api/submit documents field schema, no authentication and '
           'POST route. Duplicate returns 409. Link type and review time unstated. Rev-share '
           'bundle invitation is separate, not automatic participation. Sources: '
           'https://mcpcollection.com/submit ; https://mcpcollection.com/api/submit',
  'submit_steps': ['Provide server name, tagline, category, review email and at least one '
                   'repository/homepage/endpoint URL',
                   'Submit via web form or documented JSON API',
                   'Hosted endpoint handshake checked; accepted submissions wait for manual '
                   'review'],
  'last_verified': '2026-10-07'},
 {'name': 'llmstxt.info',
  'url': 'https://llmstxt.info/',
  'submit_url': 'https://llmstxt.info/submit/?lang=en',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': '',
  'link_type': '',
  'review_time': 'Within 48 hours editorial review (Standard free plan)',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Free Standard directory entry explicitly offered; paid expanded listings and '
           'monitoring separate. No account needed for check/generator, but listing account '
           'requirement not verified. No ranking/indexing/AI-mention guarantee per own FAQ. Plan '
           'badges are site display labels, not a verified reciprocal-site requirement. Link type '
           'left blank pending direct inspection. Sources: https://llmstxt.info/ ; '
           'https://llmstxt.info/submit/?lang=en',
  'submit_steps': ['Choose Standard Free, not a paid listing or monitoring plan',
                   'Create or provide llms.txt',
                   'Complete organization and notification details',
                   'Submit for editorial review'],
  'last_verified': '2026-10-07'},
 {'name': 'MCP.Directory',
  'url': 'https://mcp.directory/',
  'submit_url': 'https://mcp.directory/submit',
  'free_or_paid': '',
  'requires_account': '',
  'link_type': '',
  'review_time': 'Within 24 hours (site-stated)',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Metadata fetched from GitHub. Pricing/account/link-type not explicitly verified on '
           'source page. No auto-approval promise inferred. Source: https://mcp.directory/submit',
  'submit_steps': ['Provide GitHub server repository',
                   'Optionally add npm/PyPI package and short description',
                   'Provide review notification details and submit'],
  'last_verified': '2026-10-07'},
 {'name': 'skillz.directory',
  'url': 'https://skillz.directory/',
  'submit_url': 'https://skillz.directory/submit',
  'free_or_paid': '',
  'requires_account': '',
  'link_type': '',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Agent skill submissions reviewed before publication. Pricing/account/link-type/review '
           'duration not stated in page read. Source: https://skillz.directory/submit',
  'submit_steps': ['Provide skill description and repository containing SKILL.md',
                   'Provide approval notification contact',
                   'Submit for review'],
  'last_verified': '2026-10-07'},
 {'name': 'skillsdirectory.co',
  'url': 'https://skillsdirectory.co/',
  'submit_url': 'https://skillsdirectory.co/submit',
  'free_or_paid': '',
  'requires_account': '',
  'link_type': '',
  'review_time': 'Worthiness gate within 24 hours; Tier A indexed about 48 hours',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Tier A indexed; Tier B listing noindex until more signal; Tier C declined. A listing '
           'is not necessarily indexed. Pricing/account/link type unstated. Source: '
           'https://skillsdirectory.co/submit',
  'submit_steps': ['Provide fetchable GitHub, package, MCP registry or other supported capability '
                   'source URL',
                   'Identify author/user/third-party relationship and optional context',
                   'Submit for worthiness gate'],
  'last_verified': '2026-10-07'},
 {'name': 'SkillsLookup',
  'url': 'https://skillslookup.com/',
  'submit_url': 'https://skillslookup.com/submit-skill',
  'free_or_paid': '',
  'requires_account': '',
  'link_type': '',
  'review_time': 'Typically within 48 hours',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Accepts agent skills and MCP servers. Maintenance, setup documentation and '
           'reproducible examples considered. Pricing/account/link type not stated. Source: '
           'https://skillslookup.com/submit-skill',
  'submit_steps': ['Provide direct repository URL and skill name',
                   'Describe outcomes accurately with category and documentation',
                   'Submit for manual review'],
  'last_verified': '2026-10-07'},
 {'name': 'llmstxt.site',
  'url': 'https://llmstxt.site/',
  'submit_url': 'https://llmstxt.site/submit',
  'free_or_paid': '',
  'requires_account': '',
  'link_type': '',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Directory of llms.txt locations. No stated review duration, account requirement, '
           'pricing or outbound link type in form read. Source: https://llmstxt.site/submit',
  'submit_steps': ['Provide product name and llms.txt URL',
                   'Add llms-full.txt URL and contextual notes if available',
                   'Submit directory suggestion'],
  'last_verified': '2026-10-07'},
 {'name': 'CuratedMCP',
  'url': 'https://www.curatedmcp.com/',
  'submit_url': 'https://www.curatedmcp.com/publish',
  'free_or_paid': 'free_with_paid_options',
  'requires_account': '',
  'link_type': '',
  'review_time': '',
  'dr': '',
  'dr_source': '',
  'ai_agent_friendly': '',
  'notes': 'Free core listing explicitly stated; security certification and monetization optional, '
           'not included evidence of certification. Account/review duration/outbound-link type '
           'unknown. Six-client installation configs advertised, not independently tested. Source: '
           'https://www.curatedmcp.com/publish',
  'submit_steps': ['Provide server name, GitHub URL, tagline and install command',
                   'Publish using directory listing route'],
  'last_verified': '2026-10-07'}]

def full(row):
    out = {k: row.get(k, "") for k in FIELDS}
    out["submit_steps"] = row.get("submit_steps", [])
    return out

def main():
    data = [full(r) for r in ROWS]
    with open("directories.json", "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    with open("directories.csv", "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(FIELDS)
        for r in data:
            w.writerow([" > ".join(r[k]) if k == "submit_steps" else r[k] for k in FIELDS])

if __name__ == "__main__":
    main()

